language: ruby
cache: bundler
dist: xenial

before_install:
  - gem update --system
  - gem install bundler || true

rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6

branches:
  only:
    - master

bundler_args: --jobs 7 --without docs debug

script: bundle exec rake
