before_install:
  - gem update --system
  - gem install bundler

rvm:
  - 2.1.1
  - 2.2
  - 2.3

branches:
  only:
    - master

# The integration tests need to see installed gems.
script: rspec --color --format progress

