language: ruby
cache: bundler
dist: xenial

before_install:
  - gem update --system
  - gem install bundler || true

rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6

branches:
  only:
    - master

install:
  - bundle install --jobs 3 --retry 3

# The integration tests need to see installed gems.
script: rspec --color --format progress
